services:
  - type: web
    name: khet2kitchen
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn k2k.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_ovy2S0LDVQbf@ep-frosty-butterfly-azfq7ty3-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      - key: SARVAM_API_BASE_URL
        value: "https://api.sarvam.ai"
      - key: GEMINI_MODEL_NAME
        value: "gemini-2.5-flash"

