# Generated by Django 5.1.15 on 2026-09-06 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Crop Name')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Crop Code')),
                ('category', models.CharField(choices=[('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('GRAIN', 'Grain & Cereal'), ('PULSE', 'Pulse / Legume'), ('SPICE', 'Spice')], default='VEGETABLE', max_length=30, verbose_name='Category')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Baseline standard price per kg for Grade B produce.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price (₹/kg)')),
                ('shelf_life_days', models.PositiveIntegerField(help_text='Typical shelf life in days under ambient micro-hub conditions.', verbose_name='Shelf Life (Days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MicroHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Hub Name')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Hub Code')),
                ('location', models.CharField(max_length=255, verbose_name='Address / Village / Tehsil')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('pincode', models.CharField(max_length=10, verbose_name='PIN Code')),
                ('capacity_kg', models.DecimalField(decimal_places=2, help_text='Maximum physical storage capacity in kilograms.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Storage Capacity (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Micro Hub',
                'verbose_name_plural': 'Micro Hubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('identifier', models.CharField(db_index=True, help_text='Mobile number for farmers; Email address for retailers, suppliers, and admins.', max_length=255, unique=True, verbose_name='Login Identifier')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919876543210' or '9876543210' (10 to 15 digits).", regex='^\\+?[1-9]\\d{9,14}$')], verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('RETAILER', 'Retailer'), ('SUPPLIER', 'Supplier'), ('ADMIN', 'Admin')], db_index=True, default='FARMER', max_length=20, verbose_name='User Role')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='PIN Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='DemandOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='Order Identifier')),
                ('required_volume_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Required Volume (kg)')),
                ('required_date', models.DateField(help_text='The date by which the retailer needs produce delivered.', verbose_name='Required Delivery Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Matching'), ('ALLOCATED', 'Batches Allocated'), ('DISPATCHED', 'Dispatched from Hub'), ('FULFILLED', 'Fulfilled & Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30, verbose_name='Order Status')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Delivery Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_orders', to='core.crop', verbose_name='Crop')),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'RETAILER'}, on_delete=django.db.models.deletion.CASCADE, related_name='demand_orders', to=settings.AUTH_USER_MODEL, verbose_name='Retailer')),
            ],
            options={
                'verbose_name': 'Demand Order',
                'verbose_name_plural': 'Demand Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='Batch Identifier')),
                ('volume_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Volume (kg)')),
                ('ai_grade', models.CharField(choices=[('A', 'Grade A (Export / Premium)'), ('B', 'Grade B (Standard Retail)'), ('C', 'Grade C (Processing / Economy)')], default='B', max_length=1, verbose_name='AI Grade')),
                ('ai_confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence percentage score from computer vision quality assessment (0 - 100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='AI Confidence Score (%)')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received at Hub'), ('QUALITY_INSPECTED', 'AI Quality Graded'), ('ALLOCATED', 'Allocated to Demand Orders'), ('IN_TRANSIT', 'In Transit to Retailer'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], db_index=True, default='RECEIVED', max_length=30, verbose_name='Batch Status')),
                ('harvest_date', models.DateField(default=django.utils.timezone.now, verbose_name='Harvest Date')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_batches', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.crop', verbose_name='Crop')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.microhub', verbose_name='Micro Hub')),
            ],
            options={
                'verbose_name': 'Harvest Batch',
                'verbose_name_plural': 'Harvest Batches',
                'ordering': ['-received_at'],
            },
        ),
    ]
