# Generated by Django 5.1.15 on 2026-09-06 09:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Balance (₹)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('farmer', models.OneToOneField(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Farmer Wallet',
                'verbose_name_plural': 'Farmer Wallets',
            },
        ),
        migrations.CreateModel(
            name='HarvestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateField(verbose_name='Recommended Harvest Date')),
                ('target_volume_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Target Volume (kg)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Harvest'), ('COMPLETED', 'Completed & Dropped Off'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Schedule Status')),
                ('notes', models.TextField(blank=True, help_text='AI recommendation regarding weather window, sugar/brix content, or demand surge.', verbose_name='AI Agronomy Advice')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_schedules', to='core.crop', verbose_name='Crop')),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Harvest Schedule',
                'verbose_name_plural': 'Harvest Schedules',
                'ordering': ['recommended_date'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount (₹)')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Produce Payout)'), ('DEBIT', 'Debit (Bank Withdrawal)')], default='CREDIT', max_length=10, verbose_name='Transaction Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.farmerwallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
