# Generated by Django 5.1.15 on 2026-09-07 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farmerwallet_harvestschedule_wallettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AddField(
            model_name='crop',
            name='expected_yield_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Expected Yield (kg)'),
        ),
        migrations.AddField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'FARMER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL, verbose_name='Farmer'),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Harvest Date'),
        ),
        migrations.AddField(
            model_name='crop',
            name='planted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Planted Date'),
        ),
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.CharField(default='Growing', max_length=30, verbose_name='Crop Status'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Baseline standard price per kg for Grade B produce.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Base Price (₹/kg)'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Crop Code'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Crop Name'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=20, help_text='Typical shelf life in days under ambient micro-hub conditions.', verbose_name='Shelf Life (Days)'),
        ),
        migrations.CreateModel(
            name='InputSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Item / Product Name')),
                ('category', models.CharField(choices=[('FERTILIZER', 'Organic Fertilizer / Nutrients'), ('SEED', 'Certified Seeds & Seedlings'), ('EQUIPMENT', 'Irrigation & Agri-Tools'), ('PESTICIDE', 'Bio-Pesticide / Crop Care'), ('PACKAGING', 'Crates & Storage Packaging')], default='FERTILIZER', max_length=30, verbose_name='Category')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Quantity')),
                ('unit', models.CharField(default='Bags', max_length=30, verbose_name='Unit')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per Unit (₹)')),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock (Warehouse)'), ('CONSIGNED', 'Consigned at Micro-Hub'), ('RESERVED', 'Reserved by Farmer'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=30, verbose_name='Inventory Status')),
                ('description', models.TextField(blank=True, verbose_name='Specifications / Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_inputs', to='core.microhub', verbose_name='Assigned Micro-Hub')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='input_supplies', to=settings.AUTH_USER_MODEL, verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Input Supply',
                'verbose_name_plural': 'Input Supplies',
                'ordering': ['-created_at'],
            },
        ),
    ]
