# Generated by Django 5.1.15 on 2026-09-07 12:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crop_options_crop_expected_yield_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Customer Phone')),
                ('customer_email', models.EmailField(blank=True, max_length=255, verbose_name='Customer Email')),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='PIN Code')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('PAID_SETTLED', 'Paid & Farmer Settled'), ('PACKED', 'Packed at Micro-Hub'), ('DISPATCHED', 'Out for Cold Delivery'), ('DELIVERED', 'Delivered to Kitchen'), ('CANCELLED', 'Cancelled')], default='PAID_SETTLED', max_length=30)),
                ('payment_method', models.CharField(default='UPI_INSTANT', max_length=30)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumer D2C Order',
                'verbose_name_plural': 'Consumer D2C Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kit Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kit Code')),
                ('category', models.CharField(choices=[('VEGETABLE', 'Fresh Vegetables'), ('FRUIT', 'Seasonal Fruits'), ('HERBS', 'Fresh Herbs & Greens'), ('COMBO', 'Curated Box / Combo')], default='COMBO', max_length=30, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description / Highlights')),
                ('badge_text', models.CharField(blank=True, default='15% OFF', max_length=50, verbose_name='Promotional Badge')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))], verbose_name='Bundle Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active in Store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumer Kit',
                'verbose_name_plural': 'Consumer Kits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_id', models.CharField(editable=False, max_length=60, unique=True, verbose_name='Combo Identifier')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Dish Name')),
                ('servings', models.PositiveIntegerField(default=4, verbose_name='Servings Count')),
                ('prep_time_minutes', models.PositiveIntegerField(default=30, verbose_name='Estimated Prep Time (mins)')),
                ('culinary_notes', models.TextField(blank=True, verbose_name='Culinary Notes / Tips')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Total Weight (kg)')),
                ('original_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Undiscounted Price (₹)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Bundle Discount (%)')),
                ('combo_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discounted Combo Price (₹)')),
                ('items_breakdown', models.JSONField(blank=True, default=list, help_text='List of ingredients with crop_name, quantity_grams, role, and price.', verbose_name='Ingredients Breakdown JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipe Combo',
                'verbose_name_plural': 'Recipe Combos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='inputsupply',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock (Warehouse)'), ('LOW_STOCK', 'Low Stock (Reorder Alert)'), ('CONSIGNED', 'Consigned at Micro-Hub'), ('RESERVED', 'Reserved by Farmer'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=30, verbose_name='Inventory Status'),
        ),
        migrations.CreateModel(
            name='ConsumerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCE', 'Direct Farm Produce'), ('KIT', 'Pre-Packaged Kit'), ('COMBO', 'AI Recipe Combo')], default='PRODUCE', max_length=20)),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit', models.CharField(default='kg', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Net direct payout credited to the farmer's wallet (e.g. 90% of subtotal).", max_digits=10)),
                ('is_settled_to_wallet', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.crop')),
                ('farmer', models.ForeignKey(blank=True, limit_choices_to={'role': 'FARMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d2c_sales', to=settings.AUTH_USER_MODEL, verbose_name='Farmer Producer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.consumerorder')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kit')),
                ('recipe_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recipecombo')),
            ],
            options={
                'verbose_name': 'Consumer Order Item',
                'verbose_name_plural': 'Consumer Order Items',
            },
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.PositiveIntegerField(default=500, help_text='Produce weight in grams included in each kit bundle.', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Quantity (Grams)')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_appearances', to='core.crop', verbose_name='Crop Produce')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.kit', verbose_name='Kit')),
            ],
            options={
                'verbose_name': 'Kit Item',
                'verbose_name_plural': 'Kit Items',
                'unique_together': {('kit', 'crop')},
            },
        ),
    ]
