# Generated by Django 5.1.15 on 2026-09-07 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumerorder_kit_recipecombo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Registered Customer Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('RETAILER', 'Retailer'), ('SUPPLIER', 'Supplier'), ('CONSUMER', 'Consumer'), ('ADMIN', 'Admin')], db_index=True, default='FARMER', max_length=20, verbose_name='User Role'),
        ),
        migrations.CreateModel(
            name='ConsumerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Overall Rating (1-5)')),
                ('freshness_rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Produce Freshness Rating (1-5)')),
                ('delivery_rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Cold Delivery Speed Rating (1-5)')),
                ('comment', models.TextField(verbose_name='Customer Feedback')),
                ('farmer_note', models.TextField(blank=True, help_text='Heartfelt appreciation message passed directly to the farmer.', verbose_name='Direct Message / Note to Farmer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Consumer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.consumerorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Consumer Feedback',
                'verbose_name_plural': 'Consumer Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
