# Generated by Django 6.1.1 on 2026-09-07 12:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consumerorder_user_alter_user_role_consumerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandorder',
            name='channel',
            field=models.CharField(choices=[('B2B', 'B2B Wholesale (Institutional / Restaurant Bulk)'), ('COMMUNITY', 'Community Weekly Markets (RWA Pre-Order)')], db_index=True, default='B2B', help_text='B2B for institutional wholesale or COMMUNITY for weekly apartment subscription drops.', max_length=20, verbose_name='Distribution Channel'),
        ),
        migrations.AddField(
            model_name='demandorder',
            name='delivery_community_name',
            field=models.CharField(blank=True, help_text='e.g. Green Meadows Pavilion, Jubilee Hills (for Community Drops)', max_length=150, verbose_name='RWA Community / Society Name'),
        ),
        migrations.AddField(
            model_name='demandorder',
            name='input_advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retail value of seeds/fertilizers advanced to farmer to be cleared upon harvest.', max_digits=10, verbose_name='Input Advance Deduction (₹)'),
        ),
        migrations.AddField(
            model_name='demandorder',
            name='num_households',
            field=models.PositiveIntegerField(default=1, help_text='Number of participating families for community aggregated drops.', verbose_name='Household Count'),
        ),
        migrations.AddField(
            model_name='demandorder',
            name='supplier_cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform procurement cost owed back to input manufacturer.', max_digits=10, verbose_name='Supplier Wholesale Cost (₹)'),
        ),
        migrations.AddField(
            model_name='demandorder',
            name='target_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Wholesale rate (e.g. ₹30/kg) for B2B or premium retail rate (e.g. ₹45/kg) for community boxes.', max_digits=10, verbose_name='Agreed Price per kg (₹)'),
        ),
        migrations.AlterField(
            model_name='demandorder',
            name='required_date',
            field=models.DateField(help_text='The date by which produce needs to be delivered.', verbose_name='Required Delivery Date'),
        ),
        migrations.AlterField(
            model_name='demandorder',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyer / Retailer / Coordinator'),
        ),
    ]
