# Generated by Django 6.1.1 on 2026-09-07 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_demandorder_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandorder',
            name='target_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wholesale rate (e.g. ₹30/kg) for B2B or premium retail rate (e.g. ₹45/kg) for community boxes.', max_digits=10, verbose_name='Agreed Price per kg (₹)'),
        ),
    ]
