# Generated by Django 6.1.1 on 2026-09-07 13:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_demandorder_target_price_per_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['name'], 'verbose_name': 'Produce Kit / Wholesale Combo', 'verbose_name_plural': 'Produce Kits & Wholesale Combos'},
        ),
        migrations.AddField(
            model_name='kit',
            name='bulk_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total weight of the bulk wholesale package (e.g., 25.00kg, 50.00kg).', max_digits=8, verbose_name='Pack Bulk Weight (kg)'),
        ),
        migrations.AddField(
            model_name='kit',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Designated rural aggregation hub supplying this wholesale combo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_combos', to='core.microhub', verbose_name='Source Micro-Hub'),
        ),
        migrations.AddField(
            model_name='kit',
            name='is_wholesale',
            field=models.BooleanField(db_index=True, default=False, help_text='True for B2B wholesale combos designed for retailers, restaurants, and kirana stores.', verbose_name='Is Wholesale Bulk Combo'),
        ),
        migrations.AddField(
            model_name='kit',
            name='origin_cluster',
            field=models.CharField(blank=True, help_text='e.g. Medchal Peri-Urban FPO Cluster, Telangana', max_length=150, verbose_name='Farm Cluster / FPO Origin'),
        ),
        migrations.AddField(
            model_name='kit',
            name='target_audience',
            field=models.CharField(choices=[('CONSUMER', 'Consumer (D2C)'), ('RETAILER', 'Retailer (B2B Wholesale)')], db_index=True, default='CONSUMER', max_length=20, verbose_name='Target Audience'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tiered_pricing_json',
            field=models.JSONField(blank=True, default=dict, help_text="Volume discount brackets e.g. {'1-4': 2500, '5-9': 2350, '10+': 2200}.", verbose_name='Tiered Pricing Tiers'),
        ),
        migrations.AlterField(
            model_name='kititem',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.kit', verbose_name='Kit / Combo'),
        ),
        migrations.CreateModel(
            name='RetailerBulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity (Packs)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price (₹)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price (₹)')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Weight (kg)')),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('ALLOCATED', 'Stock Allocated at Micro-Hub'), ('DISPATCHED', 'Dispatched in Bulk Cold-Chain'), ('DELIVERED', 'Delivered to Retailer'), ('CANCELLED', 'Cancelled')], default='ALLOCATED', max_length=30, verbose_name='Order Status')),
                ('payment_status', models.CharField(default='PAID_INSTANT', max_length=30, verbose_name='Payment Status')),
                ('payment_ref', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference / UPI TXN')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Delivery Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_orders', to='core.kit', verbose_name='Wholesale Combo')),
                ('demand_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_orders', to='core.demandorder', verbose_name='Linked Demand Order')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_bulk_orders', to='core.microhub', verbose_name='Dispatch Micro-Hub')),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'RETAILER'}, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_bulk_orders', to=settings.AUTH_USER_MODEL, verbose_name='Retailer / Buyer')),
            ],
            options={
                'verbose_name': 'Retailer Bulk Combo Order',
                'verbose_name_plural': 'Retailer Bulk Combo Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
